### PR TITLE
Removed sed command and replace with go script

### LINKED ISSUE #1: sed: 1: "sedcmd1.txt": unterminated substitute pattern
Have the same version of protoc as you and its on my path but it bails at the SED command

```

./protoc --version
libprotoc 3.11.4

cd /Users/apple/workspace/go/src/github.com/ctessum/cityaq && go generate ./...
go: downloading github.com/golang/mock v1.4.3
go: downloading github.com/cenkalti/backoff v2.0.0+incompatible
go: downloading golang.org/x/net v0.0.0-20190620200207-3b0461eec859
go: downloading github.com/paulmach/orb v0.1.5
go: downloading github.com/ctessum/geom v0.2.10-0.20200417141930-c1ad83ff7e0d
go: downloading google.golang.org/grpc v1.28.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/spatialmodel/inmap v1.7.1-0.20200423154905-cc9fdf1215d7
go: downloading k8s.io/client-go v10.0.0+incompatible
go: downloading github.com/johanbrandhorst/grpc-wasm v0.0.0-20180613181153-d79a93c3901e
go: downloading github.com/lpar/gzipped v1.1.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/ctessum/go-leaflet v0.0.0-20190930105439-32c1547876af
go: downloading github.com/improbable-eng/grpc-web v0.11.0
go: downloading github.com/ctessum/requestcache v1.0.1
go: downloading gonum.org/v1/gonum v0.0.0-20191009222026-5d5638e6749a
go: downloading k8s.io/apimachinery v0.0.0-20190223094358-dcb391cde5ca
go: downloading gonum.org/v1/plot v0.0.0-20190615073203-9aa86143727f
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc
go: downloading k8s.io/api v0.0.0-20190111032252-67edc246be36
go: downloading cloud.google.com/go v0.44.3
go: downloading github.com/golang/gddo v0.0.0-20190904175337-72a348e765d2
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading github.com/ctessum/requestcache/v3 v3.0.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/googleapis/gnostic v0.2.0
go: downloading github.com/ctessum/polyclip-go v1.0.2-0.20200417141046-48e92ea36ddd
go: downloading k8s.io/klog v0.1.0
go: downloading github.com/peterbourgon/diskv v2.0.1+incompatible
go: downloading google.golang.org/api v0.8.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading github.com/andybalholm/brotli v0.0.0-20190821151343-b60f0d972eeb
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/google/btree v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
go: downloading github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: downloading github.com/ctessum/unit v0.0.0-20160621200450-755774ac2fcb
go: downloading go.opencensus.io v0.22.0
go: downloading github.com/ajstarks/svgo v0.0.0-20180226025133-644b8db467af
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading github.com/json-iterator/go v1.1.5
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading golang.org/x/sys v0.0.0-20190712062909-fae7ac547cb7
go: downloading github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0
go: downloading github.com/ctessum/sparse v0.0.0-20181201011727-57d6234a2c9d
go: downloading github.com/gogo/protobuf v1.3.0
go: downloading golang.org/x/image v0.0.0-20190227222117-0694c2d4d067
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
go: downloading golang.org/x/crypto v0.0.0-20190605123033-f99c8df09eb5
go: downloading github.com/google/gofuzz v0.0.0-20170612174753-24818f796faf
go: downloading github.com/jonas-p/go-shp v0.1.2-0.20190401125246-9fd306ae10a6
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/jung-kurt/gofpdf v1.0.3-0.20190309125859-24315acbbda5
go: downloading github.com/fogleman/gg v1.2.1-0.20190220221249-0403632d5b90
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/gonum/floats v0.0.0-20181209220543-c233463c7e82
go: downloading github.com/gonum/internal v0.0.0-20181124074243-f884aa714029
go: downloading github.com/spf13/cobra v0.0.0-20180531180338-1e58aa3361fd
go: downloading github.com/skratchdot/open-golang v0.0.0-20160302144031-75fb7ed4208c
go: downloading gocloud.dev v0.9.0
go: downloading github.com/ctessum/gobra v0.0.0-20180516235632-ddfa5eeb3017
go: downloading github.com/ctessum/cdf v0.0.0-20181201011353-edced208ea9d
go: downloading github.com/lnashier/viper v0.0.0-20180730210402-cc7336125d12
go: downloading github.com/spf13/cast v1.2.0
go: downloading github.com/ctessum/atmos v0.0.0-20170526022537-cba69f7ca647
go: downloading github.com/Knetic/govaluate v3.0.0+incompatible
go: downloading github.com/ctessum/requestcache/v4 v4.0.0
go: downloading github.com/spf13/afero v1.0.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/paulmach/osm v0.1.0
go: downloading github.com/aws/aws-sdk-go v1.17.6
go: downloading github.com/spf13/pflag v1.0.1
go: downloading github.com/mattn/go-sqlite3 v1.11.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/hashicorp/hcl v0.0.0-20171017181929-23c074d0eceb
go: downloading github.com/pelletier/go-toml v1.0.1
go: downloading github.com/google/wire v0.2.0
go: downloading github.com/magiconair/properties v1.7.3
go: downloading github.com/ctessum/requestcache/v2 v2.0.0
go: downloading github.com/evanphx/json-patch v4.1.0+incompatible
go: downloading github.com/mitchellh/mapstructure v0.0.0-20171017171808-06020f85339e
go: downloading github.com/spf13/jwalterweatherman v0.0.0-20170901151539-12bd96e66386
go: downloading k8s.io/kube-openapi v0.0.0-20181106182614-a9a16210091c
go: downloading github.com/tealeg/xlsx v1.0.3
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.4.2
go: google.golang.org/protobuf upgrade => v1.25.0
2020/07/16 16:44:02 WARNING: Missing 'go_package' option in "cityaq.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

sed: 1: "sedcmd1.txt": unterminated substitute pattern
gendoc.go:15: running "sed": exit status 1
make: *** [gen] Error 1
```

### PR DESCRIPTION
**Pull request by ctessum**
Fixes #1

### CODE REVIEW

**Comment by joe-getcouragenow** [comment]
Thanks.

The AddTags idea is pretty smart !!!

Just did a trial run now on on the SED branch.
A couple of things...

1.  Fix for line 19 of gendoc.go. You assume the go path is the same on everyones machine :)
``` //go:generate bash -c "mv $GOPATH/bin/protoc-gen-wasm $GOPATH/bin/protoc-gen-go" ``` 

2. I think the other lines are working. Hard to know, so i copied the other go generate lines into a make file. Makes it easir to see whats going on line by line and then checking it works as it should.

Make file:
````
client-build:

	# This replicates what the go generate does.

	@echo

	@echo -- Client dep --
	cd $(LIB_FSPATH) && go get github.com/golang/mock/gomock 
	cd $(LIB_FSPATH) && go install github.com/golang/mock/mockgen
	@echo 

	@echo -- Client WASM build --
	cd $(LIB_FSPATH) && GOOS=js GOARCH=wasm go build -o ./gui/html/cityaq.wasm ./gui/cmd/main.go
	cd $(LIB_FSPATH)/gui/html && ls -al
	@echo

	#@echo -- Client Compression ( takes a long time ) --
	#cd $(LIB_FSPATH) && go run internal/compress/main.go
	#cd $(LIB_FSPATH) && rm ./gui/html/cityaq.wasm
	#cd $(LIB_FSPATH)/gui/html && ls -al
	#@echo
	
	@echo -- Client Update WASM runners --
	@echo  GOROOT:  $(GOROOT)
	cp $(GOROOT)/misc/wasm/wasm_exec.html $(LIB_FSPATH)/gui/html/index.html
	cp $(GOROOT)/misc/wasm/wasm_exec.js $(LIB_FSPATH)/gui/html/wasm_exec.js
	cd $(LIB_FSPATH)/gui/html && ls -al
	@echo

	@echo -- Client Pack into bindata --
	go-bindata --pkg cityaq -o $(LIB_FSPATH)/assets.go $(LIB_FSPATH)/gui/html/
	@echo
````
 


Final Log of go generate is:

```
cd /Users/apple/workspace/go/src/github.com/ctessum/cityaq && go generate ./...
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.4.2
go: google.golang.org/protobuf upgrade => v1.25.0
2020/07/23 11:43:09 WARNING: Deprecated use of 'go_package' option without a full import path in "cityaq.proto", please specify:
        option go_package = ".;cityaqrpc";
A future release of protoc-gen-go will require the import path be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

go: found github.com/johanbrandhorst/grpc-wasm/protoc-gen-wasm in github.com/johanbrandhorst/grpc-wasm v0.0.0-20180613181153-d79a93c3901e
go: google.golang.org/protobuf upgrade => v1.25.0
go: github.com/golang/protobuf upgrade => v1.4.2

```


Then to run:

````

cd /Users/apple/workspace/go/src/github.com/ctessum/cityaq && go run ./cmd .
# github.com/ctessum/cityaq/cmd
cmd/main.go:36:4: unknown field 'SrgSpec' in struct literal of type aeputil.SpatialConfig
cmd/main.go:37:4: unknown field 'SrgSpecType' in struct literal of type aeputil.SpatialConfig
cmd/main.go:45:3: unknown field 'SMOKESrgSpecs' in struct literal of type cityaq.CityAQ
make: *** [server-run] Error 2

````

**Comment by joe-getcouragenow** [comment]
I have a suggestion.

1. Shall we start to use github actions, so we can build for win, mac and linux ? 
- Its very easy and you can still use travis.

2. go generate is awesome and cross platform..  I think that once github actions are in it will be easy to see what things are working properly.  
- But i cant help want some small confirmations are each part runs. I was just doing a "ls -al" to see that files are being touched. Pretty useless i know but at least tells me its progressing.. Maybe you have some ideas here.

**Comment by joe-getcouragenow** [comment]
I did a better job on https://github.com/ctessum/cityaq/pull/4. Have a look..

I think we can cancel this pull request ?

**Comment by ctessum** [comment]
Github actions sounds good. I'm not exactly sure how to go about setting it up, but you're welcome to take a stab at it.

It looks like #4 is a pull request into this pull request, so we can't cancel this one, right?

The errors you get when running cmd/main are an unrelated bug, which I just fixed in 1dccc54519b59647c7444d76345fcdd76a5c46f2

There are unit tests that are meant to confirm that everything gets generated properly and is working together, but as you may have noticed the unit tests for the WASM part especially are not currently working.

**Comment by ctessum** [comment]
Just out of curiosity, what is your interest in this package? Are you interested in that air pollution part, or just the fact that is uses WASM? I'm of course glad you find it useful, but I guess I'm somewhat surprised you found it at all.

**Comment by joe-getcouragenow** [comment]
> Just out of curiosity, what is your interest in this package? Are you interested in that air pollution part, or just the fact that is uses WASM? I'm of course glad you find it useful, but I guess I'm somewhat surprised you found it at all.

The air pollution part and the WASM part.

Our project is about environmental change and part of it is monitoring.
WASM and GRPC is needed because we need to have golang code cross compiled to WASM and also to mobiles and desktop for our system. 

I found your library after finding github.com/johanbrandhorst/grpc-wasm and having a chat to him.

**Comment by joe-getcouragenow** [comment]
> Github actions sounds good. I'm not exactly sure how to go about setting it up, but you're welcome to take a stab at it.
> 

Yep i can do it. Done it before. If its OK with you i will do it on the Master branch, once the sed branch is complete.

> It looks like #4 is a pull request into this pull request, so we can't cancel this one, right?

Yeah things got a bit mixed up, but from what i can see i think that:
#4 ( https://github.com/ctessum/cityaq/pull/4 ) is a the PR that uses a Makefile to replace the go generate approach, so if everything is now ok just merge it into master.
#3 is this PR that has your addtags work around for sed, so just merge that into master too.

Once everything is in master we can pick up the pieces and then add the github actions.


> 
> The errors you get when running cmd/main are an unrelated bug, which I just fixed in [1dccc54](https://github.com/ctessum/cityaq/commit/1dccc54519b59647c7444d76345fcdd76a5c46f2)

Oh awesome. I was wondering about that. 

> 
> There are unit tests that are meant to confirm that everything gets generated properly and is working together, but as you may have noticed the unit tests for the WASM part especially are not currently working.

Yeah i have not gotten that far yet. Once everything is in master, I plan to start seeing whats what there and seeing what else we need to do.

**Comment by ctessum** [comment]
That all sounds good. Thanks.

**Pull request merged**
